### ISSUE TITLE
Did you clone "~/.myconf" repo, add new remote github branch,  and push it to Github?

### ISSUE THREAD

**Issue by wonderffee** [jmzagorski/configfiles#1]
Recently I read about StreakyCobra's elegant solution to store dotfiles, and  found your repo on Github using same technique. I'm curious how did you push your repo to Github.

It is clear that your ~/.myconf directory is a git bare repository. In my mind, a bare git repository is created for sharing,  usually as a remote repository and can be clone by others. I think is's impossible to push a bare repo to Github directly. 

At present my solution is clone "~/.myconf" repo in another directory, add new remote github branch,   and push it to Github. Do you have a better solution?

Still have another question: In my clone repo I add a new file, for example README.md file,  and push it to remote "$HOME/.myconf" repo, how do the "$HOME/" directory show the new add file?
 "config pull" is not valid, because the result of 'config remote' is empty. Some of my understand may be wrong.

**Comment by jmzagorski** [comment]
@wonderffee you create the bare repository as your first step (see the README.md), then you need to make sure you do `alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'`  to setup your home directory as your working directory (use this command if you are on linux, if you are on windows I have a powershell script). That is how you can push files since the working tree is not pointing to the bare repository, but your home directory.

If you are following the README, after you create the bare repository you must add at least one file, for example: `config add .vimrc`. Then when you type `config status` you will see one file that you can push to github. If you look at the README, all files are explicitly not tracked or else it would show my entire home directory when I do `config status`. You must explicitly do a `config add` for your files to show in `config status`.

Let me know if this helps or if I need to improve the README

**Comment by wonderffee** [comment]
Sorry, "config push" is ignored by me. In addition, "config remote add origin https://github.com/yourusername/myconf.git" is necessary.

**Comment by jmzagorski** [comment]
Thanks, I updated the README. I assume from your last comment everything works now?

**Comment by wonderffee** [comment]
Yes
